'use client'

import { createContext, useContext, useState, type ReactNode } from 'react'

export type Lang = 'en' | 'pt'

export const translations = {
  en: {
    home: 'Menu',
    search: 'Search',
    cart: 'Cart',
    profile: 'Profile',
    menuLabel: 'Menu',
    ourDishes: 'Our Dishes',
    searchPlaceholder: 'Search dishes...',
    all: 'All',
    featured: 'Featured',
    featuredSubtitle: "Chef's picks",
    fullMenu: 'Full Menu',
    searchResults: 'Results',
    noItemsFound: 'No items found',
    noItemsHint: 'Try searching for a different dish or category',
    addToCart: 'Add',
    unavailable: 'Unavailable',
    myCart: 'My Cart',
    emptyCart: 'Your cart is empty',
    emptyCartHint: 'Add items from the menu to place your order.',
    viewMenu: 'View Menu',
    clearAll: 'Clear all',
    items: 'items',
    item: 'item',
    total: 'Total',
    placeOrder: 'Place Order',
    currency: '$',
    profileTitle: 'Profile',
    visitor: 'Visitor',
    welcomeMsg: 'Welcome to our menu!',
    myCartLink: 'My Cart',
    appVersion: 'Digital Menu v1.0',
    profileSignIn: 'Sign in',
    profileCreateAccount: 'Create account',
    profileSignedInHint: 'You are signed in.',
    profileAuthNoAccount: "Don't have an account?",
    profileAuthHasAccount: 'Already have an account?',
    profileFullName: 'Full name',
    profilePhone: 'Phone',
    profileEmail: 'Email',
    profilePassword: 'Password',
    profileShowPassword: 'Show password',
    profileHidePassword: 'Hide password',
    profileSigningIn: 'Signing in...',
    profileCreating: 'Creating...',
    profileAuthInvalid: 'Invalid email or password.',
    profileAuthAdminBlocked: 'Staff accounts use the administrative login.',
    profileAuthCreatedConfirmEmail:
      'Account created. If email confirmation is required, open the link we sent, then sign in.',
    registerSmsConsentLine1:
      'Yes, I agree to receive transactional SMS messages from Brasil Bistro regarding my order, including order confirmations, status updates, delivery notifications, and cancellations.',
    registerSmsConsentLine2: 'Message frequency varies. Message and data rates may apply.',
    registerSmsConsentLine3: 'Reply STOP to opt out or HELP for assistance.',
    registerSmsConsentRequired: 'You must accept the SMS terms above to continue.',
    registerIntroBlurb:
      'Save your name, phone and email so you do not have to enter them on every order.',
    registerPreferencesTitle: 'Other preferences',
    registerPrefEmailLabel:
      'I want to receive emails with updates about my orders.',
    registerPrefCardLabel:
      'I authorize saving my card for future purchases when PayPal offers that option securely — you can confirm again at checkout.',
    checkoutTitle: 'Your details',
    checkoutIntro:
      'Enter your information to complete the order. With an account we save it for next time.',
    checkoutGuestContactTitle: 'Contact details',
    checkoutEmailHelp: 'Used for payment receipts (PayPal).',
    checkoutConnected: 'Signed in',
    checkoutGuestSavePrompt: 'Want to save your details for next orders?',
    checkoutCreateAccount: 'Create account',
    checkoutAlreadyHaveAccount: 'I already have an account',
    checkoutContinue: 'Continue to payment',
    checkoutSaving: 'Saving...',
    checkoutLoading: 'Loading...',
    checkoutErrNome: 'Enter your full name (at least 2 characters).',
    checkoutErrPhone: 'Enter a valid phone number (at least 8 digits).',
    checkoutErrEmail: 'Enter a valid email address.',
    checkoutOrderPrefsTitle: 'Preferences for this order',
    checkoutSelectAll: 'Select all',
    checkoutPrefsAllOptional: 'All options below are optional.',
    checkoutCommPrefs: 'Communication and card',
    checkoutPrefSms: 'Receive SMS with order updates.',
    checkoutBackAria: 'Back to cart',
    searchTitle: 'Search',
    searchPagePlaceholder: 'Dishes, categories...',
    results: 'Results for',
    noResults: 'No results',
    noResultsHint: 'Try different keywords',
    recentSearches: 'Recent Searches',
    adminTitle: 'Menu Admin',
    adminPanel: 'Panel',
    tabItems: 'Items',
    tabCategories: 'Categories',
    newItem: 'New Item',
    editItem: 'Edit Item',
    newCategory: 'New Category',
    editCategory: 'Edit Category',
    fieldName: 'Name *',
    fieldDesc: 'Description',
    fieldPrice: 'Price (USD) *',
    fieldImage: 'Product Image',
    fieldCategory: 'Category',
    fieldOrder: 'Order',
    fieldAvailable: 'Available',
    fieldFeatured: 'Featured',
    fieldActive: 'Active',
    fieldIcon: 'Icon (emoji)',
    noCategory: 'No category',
    placeholderName: 'Ex: Margherita Pizza',
    placeholderDesc: 'Ingredients, details...',
    placeholderPrice: 'Ex: 9.99',
    placeholderIcon: '🍽️',
    save: 'Save',
    saving: 'Saving...',
    logout: 'Logout',
    deleteItemConfirm: 'Delete this menu item?',
    deleteCatConfirm: 'Delete this category? Items will become uncategorized.',
    noItems: 'No items yet',
    noItemsHintAdmin: 'Add your first menu item.',
    addItem: 'Add Item',
    noCategories: 'No categories',
    noCategoriesHint: 'Create categories to organize the menu.',
    addCategory: 'Add Category',
    available: 'Available',
    hidden: 'Hidden',
    active: 'Active',
    inactive: 'Inactive',
    order: 'Order:',
    uploadPhoto: 'Tap to add photo',
    uploadHint: 'JPG, PNG or WebP — max 5MB',
    uploadError: 'Upload failed. Please try again.',
    fileTooLarge: 'Image too large. Max: 5MB.',
    invalidFile: 'Please select a valid image file.',
  },
  pt: {
    home: 'Cardapio',
    search: 'Busca',
    cart: 'Carrinho',
    profile: 'Perfil',
    menuLabel: 'Cardapio',
    ourDishes: 'Nossos Pratos',
    searchPlaceholder: 'Buscar pratos...',
    all: 'Todas',
    featured: 'Destaques',
    featuredSubtitle: 'Escolhas da casa',
    fullMenu: 'Cardapio Completo',
    searchResults: 'Resultados',
    noItemsFound: 'Nenhum item encontrado',
    noItemsHint: 'Tente buscar por outro prato ou categoria',
    addToCart: 'Adicionar',
    unavailable: 'Indisponivel',
    myCart: 'Carrinho',
    emptyCart: 'Carrinho vazio',
    emptyCartHint: 'Adicione itens do cardapio para fazer seu pedido.',
    viewMenu: 'Ver cardapio',
    clearAll: 'Limpar tudo',
    items: 'itens',
    item: 'item',
    total: 'Total',
    placeOrder: 'Finalizar Pedido',
    currency: '$',
    profileTitle: 'Perfil',
    visitor: 'Visitante',
    welcomeMsg: 'Bem-vindo ao nosso cardapio!',
    myCartLink: 'Meu Carrinho',
    appVersion: 'Cardapio Digital v1.0',
    profileSignIn: 'Entrar',
    profileCreateAccount: 'Criar conta',
    profileSignedInHint: 'Sua conta esta ativa neste aparelho.',
    profileAuthNoAccount: 'Nao tem conta?',
    profileAuthHasAccount: 'Ja tem conta?',
    profileFullName: 'Nome completo',
    profilePhone: 'Telefone',
    profileEmail: 'E-mail',
    profilePassword: 'Senha',
    profileShowPassword: 'Mostrar senha',
    profileHidePassword: 'Ocultar senha',
    profileSigningIn: 'Entrando...',
    profileCreating: 'Criando...',
    profileAuthInvalid: 'E-mail ou senha invalidos.',
    profileAuthAdminBlocked: 'Para equipe, use a area administrativa.',
    profileAuthCreatedConfirmEmail:
      'Conta criada. Se for preciso confirmar o e-mail, abra o link recebido e depois entre.',
    registerSmsConsentLine1:
      'Sim, concordo em receber mensagens SMS transacionais do Brasil Bistro referentes ao meu pedido, incluindo confirmações, atualizações de status, notificações de entrega e cancelamentos.',
    registerSmsConsentLine2:
      'A frequência das mensagens varia. Tarifas de mensagens e dados podem ser aplicadas.',
    registerSmsConsentLine3: 'Responda STOP para cancelar o recebimento ou HELP para obter ajuda.',
    registerSmsConsentRequired: 'Aceite os termos de SMS acima para continuar.',
    registerIntroBlurb: 'Guarde seu nome, telefone e e-mail para não repetir em cada pedido.',
    registerPreferencesTitle: 'Outras preferências',
    registerPrefEmailLabel: 'Quero receber e-mails com atualizações dos meus pedidos.',
    registerPrefCardLabel:
      'Autorizo salvar meu cartão para compras futuras, quando o PayPal oferecer essa opção de forma segura — na hora do pagamento você poderá confirmar de novo.',
    checkoutTitle: 'Seus dados',
    checkoutIntro:
      'Informe seus dados para concluir o pedido. Com uma conta, guardamos para a próxima vez.',
    checkoutGuestContactTitle: 'Dados de contato',
    checkoutEmailHelp: 'Usado no comprovante de pagamento (PayPal).',
    checkoutConnected: 'Conta conectada',
    checkoutGuestSavePrompt: 'Quer guardar seus dados para os próximos pedidos?',
    checkoutCreateAccount: 'Criar conta',
    checkoutAlreadyHaveAccount: 'Já tenho conta',
    checkoutContinue: 'Continuar para pagamento',
    checkoutSaving: 'Salvando...',
    checkoutLoading: 'Carregando...',
    checkoutErrNome: 'Informe seu nome completo (mínimo 2 letras).',
    checkoutErrPhone: 'Informe um telefone válido (mínimo 8 dígitos).',
    checkoutErrEmail: 'Informe um e-mail válido.',
    checkoutOrderPrefsTitle: 'Preferências deste pedido',
    checkoutSelectAll: 'Marcar todos',
    checkoutPrefsAllOptional: 'Todas as opções abaixo são opcionais.',
    checkoutCommPrefs: 'Comunicação e cartão',
    checkoutPrefSms: 'Receber SMS com atualizações do pedido.',
    checkoutBackAria: 'Voltar ao carrinho',
    searchTitle: 'Buscar',
    searchPagePlaceholder: 'Pratos, categorias...',
    results: 'Resultados para',
    noResults: 'Sem resultados',
    noResultsHint: 'Tente palavras diferentes',
    recentSearches: 'Buscas Recentes',
    adminTitle: 'Admin Cardapio',
    adminPanel: 'Painel',
    tabItems: 'Itens',
    tabCategories: 'Categorias',
    newItem: 'Novo Item',
    editItem: 'Editar Item',
    newCategory: 'Nova Categoria',
    editCategory: 'Editar Categoria',
    fieldName: 'Nome *',
    fieldDesc: 'Descricao',
    fieldPrice: 'Preco (USD) *',
    fieldImage: 'Imagem do Produto',
    fieldCategory: 'Categoria',
    fieldOrder: 'Ordem',
    fieldAvailable: 'Disponivel',
    fieldFeatured: 'Destaque',
    fieldActive: 'Ativa',
    fieldIcon: 'Icone (emoji)',
    noCategory: 'Sem categoria',
    placeholderName: 'Ex: Pizza Margherita',
    placeholderDesc: 'Ingredientes, detalhes...',
    placeholderPrice: 'Ex: 9.99',
    placeholderIcon: '🍽️',
    save: 'Salvar',
    saving: 'Salvando...',
    logout: 'Sair',
    deleteItemConfirm: 'Excluir este item do cardapio?',
    deleteCatConfirm: 'Excluir esta categoria? Os itens associados ficarao sem categoria.',
    noItems: 'Nenhum item cadastrado',
    noItemsHintAdmin: 'Crie o primeiro item do seu cardapio.',
    addItem: 'Adicionar Item',
    noCategories: 'Nenhuma categoria',
    noCategoriesHint: 'Crie categorias para organizar o cardapio.',
    addCategory: 'Adicionar Categoria',
    available: 'Disponivel',
    hidden: 'Oculto',
    active: 'Ativa',
    inactive: 'Inativa',
    order: 'Ordem:',
    uploadPhoto: 'Toque para adicionar foto',
    uploadHint: 'JPG, PNG ou WebP — max. 5MB',
    uploadError: 'Erro ao fazer upload. Tente novamente.',
    fileTooLarge: 'Imagem muito grande. Maximo: 5MB.',
    invalidFile: 'Selecione um arquivo de imagem valido.',
  },
} as const

type Translations = typeof translations.en

interface LangContextType {
  lang: Lang
  t: Translations
  toggleLang: () => void
}

const LangContext = createContext<LangContextType | null>(null)

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('en')
  const toggleLang = () => setLang((l) => (l === 'en' ? 'pt' : 'en'))
  const t = translations[lang]
  return (
    <LangContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  const ctx = useContext(LangContext)
  if (!ctx) throw new Error('useLang must be used within LangProvider')
  return ctx
}
